version: "3.8"

services:
  db:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    container_name: postgres-dev
    image: postgres:14.5-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - disney
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  db-bootstrap:
    build: ./
    environment:
      - ROLE=bootstrap
      - NODE_ENV=development
      - PORT=5000
      - DB_ENV=development
    restart: 'no'
    depends_on:
      - db
    networks:
      - disney
  app:
    build: ./
    ports:
      - 5000:5000
    environment:
      - ROLE=server
      - NODE_ENV=development
      - PORT=5000
      - DB_ENV=development
    restart: 'no'
    depends_on:
      - db
    networks:
      - disney

networks:
  disney:
    driver: bridge