version: "3.8"

services:
  db:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    container_name: postgres-dev
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
